### ISSUE TITLE
Error: Cannot find module 'core-js/modules/es6.regexp.split'

### ISSUE THREAD

**Issue by jonathanmach** [storyblok/storyblok-gridsome-boilerplate#2]
I keep getting this error after having run `npm install` and trying to run the project:

```bash
storyblok-gridsome-boilerplate> gridsome develop
Gridsome v0.7.13

Initializing plugins...
Error: Cannot find module 'core-js/modules/es6.regexp.split'
Require stack:
- C:\Users\jonat\Desktop\Projects\Code Projects\lab-projects\storyblok-gridsome-boilerplate\node_modules\storyblok-js-client\dist\index.js
- C:\Users\jonat\Desktop\Projects\Code Projects\lab-projects\storyblok-gridsome-boilerplate\node_modules\gridsome-source-storyblok\index.js
- C:\Users\jonat\Desktop\Projects\Code Projects\lab-projects\storyblok-gridsome-boilerplate\node_modules\gridsome\lib\app\Plugins.js
- C:\Users\jonat\Desktop\Projects\Code Projects\lab-projects\storyblok-gridsome-boilerplate\node_modules\gridsome\lib\app\App.js
- C:\Users\jonat\Desktop\Projects\Code Projects\lab-projects\storyblok-gridsome-boilerplate\node_modules\gridsome\lib\app\index.js
- C:\Users\jonat\Desktop\Projects\Code Projects\lab-projects\storyblok-gridsome-boilerplate\node_modules\gridsome\lib\develop.js
- C:\Users\jonat\Desktop\Projects\Code Projects\lab-projects\storyblok-gridsome-boilerplate\node_modules\gridsome\index.js
- C:\Users\jonat\AppData\Roaming\npm\node_modules\@gridsome\cli\bin\gridsome.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\jonat\Desktop\Projects\Code Projects\lab-projects\storyblok-gridsome-boilerplate\node_modules\storyblok-js-client\dist\index.js:15:1)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\jonat\Desktop\Projects\Code Projects\lab-projects\storyblok-gridsome-boilerplate\node_modules\gridsome-source-storyblok\index.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
```

**Comment by emanuelgsouza** [comment]
The gridsome and gridsome-source-plugin packages [was updated](https://github.com/storyblok/storyblok-gridsome-boilerplate/commit/39ab788eb5d1243c66f86e397b2c7b4792c4efed) fixing this issue.
